In [9]:
import pandas as pd

In [10]:
df = pd.read_csv(r'D:\PROJECTs\IPL predictor\archive\deliveries.csv')
df

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260915,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,5,SS Iyer,AK Markram,VR Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260916,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,6,VR Iyer,AK Markram,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260917,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,1,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260918,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,2,SS Iyer,Shahbaz Ahmed,VR Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260919,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,3,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN

In [11]:
df.isnull().sum()

match_id                 0
inning                   0
batting_team             0
bowling_team             0
over                     0
ball                     0
batter                   0
bowler                   0
non_striker              0
batsman_runs             0
extra_runs               0
total_runs               0
extras_type         246795
is_wicket                0
player_dismissed    247970
dismissal_kind      247970
fielder             251566
dtype: int64

In [12]:
df.drop(['player_dismissed', 'dismissal_kind', 'fielder', "extras_type", 'match_id'], axis=1, inplace=True)

In [13]:
df

,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,is_wicket
0,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,0
1,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,0
2,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,0
3,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,0
4,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
260915,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,5,SS Iyer,AK Markram,VR Iyer,1,0,1,0
260916,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,6,VR Iyer,AK Markram,SS Iyer,1,0,1,0
260917,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,1,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,0
260918,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,2,SS Iyer,Shahbaz Ahmed,VR Iyer,1,0,1,0
260919,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,3,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,0

In [14]:
df.isnull().sum()

inning          0
batting_team    0
bowling_team    0
over            0
ball            0
batter          0
bowler          0
non_striker     0
batsman_runs    0
extra_runs      0
total_runs      0
is_wicket       0
dtype: int64

In [15]:
df.duplicated().sum()

633

In [16]:
df.drop_duplicates(inplace=True)

In [17]:
df

,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,is_wicket
0,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,0
1,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,0
2,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,0
3,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,0
4,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
260915,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,5,SS Iyer,AK Markram,VR Iyer,1,0,1,0
260916,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,6,VR Iyer,AK Markram,SS Iyer,1,0,1,0
260917,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,1,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,0
260918,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,2,SS Iyer,Shahbaz Ahmed,VR Iyer,1,0,1,0
260919,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,3,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,0

In [18]:
# spliting into catagorical and numerical data 
catagorical = df.select_dtypes(include=['O'])
numerical = df.select_dtypes(exclude=['O'])
catagorical

,batting_team,bowling_team,batter,bowler,non_striker
0,Kolkata Knight Riders,Royal Challengers Bangalore,SC Ganguly,P Kumar,BB McCullum
1,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,SC Ganguly
2,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,SC Ganguly
3,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,SC Ganguly
4,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,SC Ganguly
...,...,...,...,...,...
260915,Kolkata Knight Riders,Sunrisers Hyderabad,SS Iyer,AK Markram,VR Iyer
260916,Kolkata Knight Riders,Sunrisers Hyderabad,VR Iyer,AK Markram,SS Iyer
260917,Kolkata Knight Riders,Sunrisers Hyderabad,VR Iyer,Shahbaz Ahmed,SS Iyer
260918,Kolkata Knight Riders,Sunrisers Hyderabad,SS Iyer,Shahbaz Ahmed,VR Iyer
260919,Kolkata Knight Riders,Sunrisers Hyderabad,VR Iyer,Shahbaz Ahmed,SS Iyer

In [19]:
numerical

        inning  over  ball  batsman_runs  extra_runs  total_runs  is_wicket
0            1     0     1             0           1           1          0
1            1     0     2             0           0           0          0
2            1     0     3             0           1           1          0
3            1     0     4             0           0           0          0
4            1     0     5             0           0           0          0
...        ...   ...   ...           ...         ...         ...        ...
260915       2     9     5             1           0           1          0
260916       2     9     6             1           0           1          0
260917       2    10     1             1           0           1          0
260918       2    10     2             1           0           1          0
260919       2    10     3             1           0           1          0

[260287 rows x 7 columns]